### ISSUE TITLE
Water in the nether and in the end

### ISSUE THREAD

**Issue by Manu5656** [BentoBoxWorld/AcidIsland#19] opened 2019-01-02 15:07 UTC
The nether and the end are generated within the water. How can I remove water from these two worlds? In the old version the water was not generated in the end and in the nether and I would like it to be so even now.

**Comment by Manu5656** [comment] 2019-01-02 15:32
No, to me it creates the world of nether and of the end within the water

**Comment by Poslovitch** [comment] 2019-01-02 15:48
Are you using AcidIsland or BSkyBlock?
Can you please provide the value set in the config for `sea-height` ?

**Comment by Manu5656** [comment] 2019-01-02 15:54
AcidIsland.  The sea-height value is set to 81 because I need it to match the schematic of the main island.

is it possible to add an option in the config to NOT make the water generate in the nether and in the end? it's much better if it's not there

**Comment by Poslovitch** [comment] 2019-01-02 16:04
Okay, then, it's a duplicate of #13. 🙂

**Closed by Poslovitch** 2019-01-02 16:04 UTC

**Comment by Manu5656** [comment] 2019-01-02 16:10
So can you make this change? Otherwise I can not open my server because although I want to leave the water in these two worlds the problem is that a different water height is necessary for the three worlds because there are different schematics and not all of them need the same height as the water.

So either add an option in the config to turn off the water in the nether and in the end or add an option that allows you to set a height for the water and for the different island for each world (So nether, end and normal world ). Let me know.

**Comment by Poslovitch** [comment] 2019-01-02 16:16
> Otherwise I can not open my server because although I want to leave the water in these two worlds the problem is that a different water height is necessary for the three worlds because there are different schematics and not all of them need the same height as the water.

Please open an issue for that.

>add an option in the config to turn off the water in the nether and in the end

This is already covered by #13.

**Comment by Manu5656** [comment] 2019-01-02 16:21
Okay, but I would need to get an answer :)

**Comment by Manu5656** [comment] 2019-01-02 16:32
Understood, I hope it will be done in a short time otherwise I am stuck and can not do anything 😅

**Comment by tastybento** [comment] 2019-01-02 16:35
Hey @Manu5656 I’ll work on this today.

**Comment by Manu5656** [comment] 2019-01-02 16:36
Many thanks! @tastybento
